apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medi
  template:
    metadata:
      labels:
        app: medi
    spec:
      containers:
      - name: medicure
        image: minimalkushal/medicure
        ports:
        - containerPort: 8082
