- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: apt update
    command: sudo apt update
  - name: Install Docker
    command: sudo apt install docker.io -y
  - name: Download Minikube
    command: sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  - name: Install Minikube
    command: sudo dpkg -i minikube_latest_amd64.deb
  - name: Start Minikube
    command: minikube start
  - name: Create Deployment
    command: sudo kubectl create deployment medicure --image=minimalkushal/medicure
  - name: Expose Medicure Project
    command: sudo kubectl expose deployment medicure --type=NodePort --port=8082
  - name: Get Services
    command: sudo kubectl get svc
    
