- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Create Deployemnt
    command: sudo kubectl apply -f deployment.yml
  - name: Create Service
    command: sudo kubectl apply -f svc.yml
  - name: Get Services
    command: sudo kubectl get svc
