- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Apt update
    command: sudo apt update
  - name: Install Docker
    command: sudo apt install docker.io -y
  - name: Install MicroK8s
    command: sudo snap install microk8s --classic
  - name: MicroK8s Status
    command: sudo microk8s status
  - name: Project Deployment
    command: sudo microk8s kubectl create deployment medicure-deploy --image=minimalkushal/medicure
  - name: Exposing the App
    command: sudo microk8s kubectl expose deployment medicure-deploy --port=8082 --type=NodePort
  - name: Get the Service Port Number
    command: sudo microk8s kubetcl get svc
